language: objective-c
before_install:
 - gem install cocoapods -v '1.4.0.rc.1'
script:
 - cd Example
 - pod install
 - xcodebuild test -workspace BugfenderExample.xcworkspace -scheme BugfenderExample -destination 'platform=iOS Simulator,name=iPhone 6'
osx_image: xcode9.2
