language: objective-c
before_install:
 - gem install cocoapods -v '1.6.1'
 - gem install jazzy -v '0.9.0'
 - brew install carthage
script:
 - pod lib lint
 - echo 'binary "https://raw.githubusercontent.com/bugfender/BugfenderSDK-iOS/master/BugfenderSDK.json" ~>1.6' > Cartfile
 - carthage update
 - ./generate-docs
 - cd Example
 - pod install
 - xcodebuild test -workspace BugfenderExample.xcworkspace -scheme BugfenderExample -destination 'platform=iOS Simulator,name=iPhone 6'
osx_image: xcode9.2
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs
  on:
    branch: master
